server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8764
#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd 
  profiles: 
    active: dev
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 50Mb
  devtools:
    restart:
      enabled: true   
  application:
    name: fastwave-service-admin
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关  
    lazyLoadingEnabled: true #延时加载的开关  
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性  
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用  
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: fastwave.**.domain
  global-config:  
    id-type: 3  #1:数据库ID自增   2:用户输入id   3:全局唯一id(IdWorker)   4:全局唯一ID(uuid)  
    db-column-underline: false  
    refresh-mapper: true

#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://10.101.43.197:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      lilizhou: BBC  # 不会影响客户端行为
    lease-renewal-interval-in-seconds: 5
    
web: 
#  upload-path: /usr/local/fastwave/upload
#  front-path: /usr/local/fastwave/front
#  upload-ip: 10.101.43.125
#  port: 8100
  upload-path: e:/myfile/upload
  front-path: e:/myfile/front
  upload-ip: localhost
  port: 8100 
  
spring.resources.static-locations: file:${web.upload-path},file:${web.front-path}


